### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [SSaapon/prj-rev-bwfs-dasmoto#1]
I like that you created section in your html with divs. I would recommend moving the id from the h2 in to the div. This will give each section it's own identifying label and you can still uniquely target the h2's via chaining:
#brushes h2 { }

https://github.com/SSaapon/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/index.html#L14-L21

**Comment by SSaapon** [comment]
That's really useful. It cleans up the code a lot. Thank you for the suggestion.
