### ISSUE TITLE
use alt attribute

### ISSUE THREAD

**Issue by rimmesbe** [SSaapon/prj-rev-bwfs-dasmoto#2]
Try to get in the habit of describing your image tags with the alt attribute. This is used by screen readers and makes your code look more professional.

https://github.com/SSaapon/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/index.html#L16

**Comment by SSaapon** [comment]
This is useful to know. It was never brought up in the course work.  I'll start using it. Thank you.
