### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [SSaapon/prj-rev-bwfs-dasmoto#3]
What you have here works, but it's not that efficient. If we had a real sized project we don't want to have to list every element we want to have the font. Instead use inheritance to set the default font for the whole page:
html { font-family: Helvetica; }
Now all elements will inherit this font from html.

https://github.com/SSaapon/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/Resources/css/style.css#L1-L3

**Comment by SSaapon** [comment]
Good suggestion, thank you. I will keep that in mind on future projects.
