### ISSUE TITLE
regarding header's

### ISSUE THREAD

**Issue by rimmesbe** [SSaapon/prj-rev-bwfs-dasmoto#4]
Div elements default to block display and header tags (h1, h2, h3...) default to bold font, so no need to add these.

https://github.com/SSaapon/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/Resources/css/style.css#L7-L10

**Comment by SSaapon** [comment]
The header gave me the most difficultly. The preview page had a neat, short, rectangular header. My header was showing up as this gigantic block. I was attempting to make it look like the former, but had not clue how to do that. Any tips?

**Comment by rimmesbe** [comment]
put the font-size directly on the h1.

**Comment by SSaapon** [comment]
Thank you, I will try it out.
