### ISSUE TITLE
good use of class

### ISSUE THREAD

**Issue by rimmesbe** [SSaapon/prj-rev-bwfs-dasmoto#5]
This is a good use of class and a good name as it describes the component being styled. You could replace the span tag with a `<strong>` tag if you want to get the bold font default and add some semantic weight to the price text.

https://github.com/SSaapon/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/Resources/css/style.css#L26-L29

**Comment by SSaapon** [comment]
Thank you for the suggestion.
