### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [SSaapon/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the page looks good. Your code is well organized and you use some good techniques. Take a look at the issues I created and see if you can implement the changes. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by SSaapon** [comment]
Thank you for providing me with that resource. I have read through it and taken notes on areas where I can improve.
